name: Github Package Registry npm Proxy
description: setup npm to use GPR as proxy

branding:
  icon: package
  color: red

inputs:
  path:
    description: path to write .npmrc file
    default: ${{ github.workspace	}}/.npmrc

  scope:
    description: the github owner / org name to proxy through
    default: ${{ github.repository_owner }}

  token:
    description: github token to use with npm
    default: ${{ github.token }}

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        npm config --userconfig "${{ inputs.path }}" set registry="https://npm.pkg.github.com/${{ inputs.scope }}"
        npm config --userconfig "${{ inputs.path }}" set //npm.pkg.github.com/:_authToken "${{ inputs.token }}"
        npm config --userconfig "${{ inputs.path }}" set always-auth true
